.SILENT: dev

all: help

dev: 
	hugo serve 
	
help:
	echo Makefile to manage the step of the blog frontend
	echo usage: make [target]
	echo With target one of : 
	echo    - dev  : Launch the hugo server in development mode
	echo    - help : Display this help