name: Commit on main in blog

on:
  pull_request:
    paths: 
      - "blog/**"
      - ".github/workflows/main_blog.yaml"

defaults:
  run:
    working-directory: blog

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v2
        with:
          hugo-version: '0.100.2'
      - name: Build website
        run: |
          hugo
          if find "$(pwd)/public" -empty | grep -q "."; then
            exit 0
          fi
          exit 1