name: Commit on main in infrastructure/codebase

on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths: 
      - "infrastructure/codebase/github/**"
      - ".github/workflows/main_infra_codebase.yaml"

env:
  TF_VERSION: 1.0.9

defaults:
  run:
    working-directory: infrastructure/codebase/github

jobs:
  apply:
    runs-on: ubuntu-latest
    permissions:
      pull-requests: 'write'
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Initialize Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: ${{ env.TF_VERSION }}
      - name: Apply TF
        id: apply
        run: |
          export AZ_STORAGE_NAME="${{ secrets.AZ_STORAGE }}"
          export AZ_RESOURCE_GROUP="${{ secrets.AZ_RGROUP }}"
          export ARM_CLIENT_ID="${{ secrets.AZ_CLIENT_ID }}"
          export ARM_CLIENT_SECRET="${{ secrets.AZ_CLIENT_SECRET }}"
          export ARM_SUBSCRIPTION_ID="${{ secrets.AZ_SUBSCRIPTION_ID }}"
          export ARM_TENANT_ID="${{ secrets.AZ_TENANT_ID }}"
          terraform init \
            -backend-config storage_account_name="$AZ_STORAGE_NAME" \
            -backend-config resource_group_name="$AZ_RESOURCE_GROUP"
          terraform apply -auto-approve -no-color -var gh_pat="${{ secrets.GH_PAT }}" -lock=false