name: Commit on main in blog

on:
  push:
    branches:
      - main
    paths: 
      - "blog/**"
      - ".github/workflows/main_blog.yaml"

defaults:
  run:
    working-directory: blog

# This action needs a deployment service principal to be stored in the secrets AZ_BLOG_DEPLOY_SA
# az ad sp create-for-rbac --name blogDeployer --role contributor --scopes /subscriptions/{subscription-id}/resourceGroups/{resource-group} --sdk-auth

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v2
        with:
          hugo-version: '0.100.2'
      - name: Build website
        run: |
          hugo
          if find "$(pwd)/public" -empty | grep -q "."; then
            echo "Directory './public' is empty"
            exit 1
          fi
          exit 0
      - name: Login to Azure
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZ_BLOG_DEPLOY_SA }}
      - name: Publish the content to Azure
        uses: azure/CLI@v1
        with:
          inlineScript: |
            az storage blob upload-batch --account-name 'an0rakblog' --auth-mode key -d '$web' -s ./blog/public
      - name: Logout from Azure
        if: always()
        run: |
          az logout