name: Build PullRequest

on:
  pull_request:
    paths:
      - .github/workflows/pr.yaml
      - src

env:
  HUGO_VERSION: "0.104.2"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Setup Hugo
        uses: ./.github/actions/setup-hugo
        with:
          version: ${{ env.HUGO_VERSION }}
      - name: Build
        uses: ./.github/actions/build-hugo
        with:
          sourceDir: "src"
          config: "config.yaml"
