name: Build PullRequest

on:
  pull_request:
    paths:
      - .github/workflows/pr.yaml
      - src

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Setup Hugo
        uses: ./.github/actions/setup-hugo
        with:
          version: "0.104.2"
      - name: Build
        uses: ./.github/actions/build-hugo
        with:
          sourceDir: "src"
          config: "config.yaml"
