name: PullRequest in blog/

on:
  pull_request:
    paths: 
      - "blog/**"
      - ".github/workflows/pr_blog.yaml"

defaults:
  run:
    working-directory: blog

jobs:
  validate:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v2
        with:
          hugo-version: '0.100.2'
      - name: Build Hugo file
        run: |
          hugo
          if find "$(pwd)/public" -empty | grep -q "."; then
            echo "Directory './public' is empty"
            exit 1
          fi
          exit 0