name: PullRequest in infrastructure/blog

on:
  pull_request:
    paths: 
      - "infrastructure/blog/**"
      - ".github/workflows/pr_infra_blog.yaml"

env:
  TF_VERSION: 1.0.9

defaults:
  run:
    working-directory: infrastructure/blog

jobs:
  validate:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Initialize Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: ${{ env.TF_VERSION }}
      - name: Check TF format
        run: terraform fmt -check 
      - name: Validate TF
        run: |
          export AZ_STORAGE_NAME="${{ secrets.AZ_STORAGE }}"
          export AZ_RESOURCE_GROUP="${{ secrets.AZ_RGROUP }}"
          export ARM_CLIENT_ID="${{ secrets.AZ_CLIENT_ID }}"
          export ARM_CLIENT_SECRET="${{ secrets.AZ_CLIENT_SECRET }}"
          export ARM_SUBSCRIPTION_ID="${{ secrets.AZ_SUBSCRIPTION_ID }}"
          export ARM_TENANT_ID="${{ secrets.AZ_TENANT_ID }}"
          terraform init \
            -backend-config storage_account_name="$AZ_STORAGE_NAME" \
            -backend-config resource_group_name="$AZ_RESOURCE_GROUP"
          terraform validate -no-color

  plan:
    runs-on: ubuntu-latest
    permissions:
      pull-requests: 'write'
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Initialize Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: ${{ env.TF_VERSION }}
      - name: Plan TF
        id: plan
        run: |
          export AZ_STORAGE_NAME="${{ secrets.AZ_STORAGE }}"
          export AZ_RESOURCE_GROUP="${{ secrets.AZ_RGROUP }}"
          export ARM_CLIENT_ID="${{ secrets.AZ_CLIENT_ID }}"
          export ARM_CLIENT_SECRET="${{ secrets.AZ_CLIENT_SECRET }}"
          export ARM_SUBSCRIPTION_ID="${{ secrets.AZ_SUBSCRIPTION_ID }}"
          export ARM_TENANT_ID="${{ secrets.AZ_TENANT_ID }}"
          terraform init \
            -backend-config storage_account_name="$AZ_STORAGE_NAME" \
            -backend-config resource_group_name="$AZ_RESOURCE_GROUP"
          terraform plan -no-color -var az_location="West Europe" -var az_resource_group="$AZ_RESOURCE_GROUP" -lock=false
      - name: Comment PR with plan
        uses: actions/github-script@v6
        with:
          script: |
            let message = `${{ steps.plan.outputs.stdout }}`;
            let completeMessage = `
            ### Plan output
            \`\`\`
                ${message}
            \`\`\`
            `;
            github.rest.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: completeMessage,
            });